services:
  - type: web
    name: eduverse-backend
    env: python
    region: oregon  # Change based on your location
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      bun install
      bun run build
      cd ..
    startCommand: "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
    # envVars:
    #   - key: MONGO_URI
    #     value: $MONGO_URI
    #   - key: JWT_SECRET
    #     value: $JWT_SECRET
    #   - key: API_KEY
    #     value: $API_KEY
    #   - key: MODEL_NAME
    #     value: $MODEL_NAME
